import {  useState, useEffect, useCallback, useMemo } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import styles from '../styles/Home.module.css';
import Header from 'molecule/Header';
import Footer from 'molecule/Footer';
import Animated from 'src/product/Loader/Animated';
import Interests from 'src/product/Loader/interests';
import Searching from 'src/product/Loader/Searching';
import Question from 'src/product/Loader/Question';
import Confirm from 'src/product/Loader/Confirm';
import Workflow from 'molecule/Workflow';

const Search = () => {
  const { query } = useRouter();

  let { firstName, lastName, state } = query;
  // query string param can come in as a string of undefined
  if (firstName === 'undefined') firstName = '';
  if (lastName === 'undefined') lastName = '';
  const target = `${firstName || ''} ${lastName || ''}`;

  const screens = useMemo(() => [
    {time: 8000, component: <Searching target={target} />},
    {time: 8000, component: <Question title={`Where has ${target} ever lived?`} fields={[{ name: 'city', type: 'text', placeholder: 'Enter City' }]} />},
    {time: 8000, component: <Interests />},
    {time: 8000, component: <Question title="Narrow Your Search Results" fields={[
      { name: 'age', type: 'select', options: [{value:"18-40", label:"18-40"}, {value:"41-60",label:"41-60"}, {value:"61-80",label:"61-80"}, {value:"80+",label:"80+"}], placeholder: 'Select Age' },
      { name: 'middleInitial', type: 'text', placeholder: 'Enter Middle Initial' },
    ]} />},
    {time: 8000, component: <Confirm onClick={() => {}}/>},
    {component: <Animated target={target} location={state as string} />},
  ], [target, state]);


  return (
    <>
      <Head>
        <title>Next POC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
      <Workflow steps={screens} />
      </main>
      <Footer />
    </>
  )
}
export default Search;